"""create journey_tracking table

Revision ID: 6d2f5450d738
Revises: 
Create Date: 2025-10-08 18:55:50.976220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d2f5450d738'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_station_name', sa.String(), nullable=True),
    sa.Column('source_lat', sa.Float(), nullable=True),
    sa.Column('source_lng', sa.Float(), nullable=True),
    sa.Column('destination_type', sa.String(), nullable=False),
    sa.Column('destination_name', sa.String(), nullable=False),
    sa.Column('destination_station_name', sa.String(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('nearest_entry_gate', sa.JSON(), nullable=True),
    sa.Column('nearest_exit_gate', sa.JSON(), nullable=True),
    sa.Column('metro_route', sa.JSON(), nullable=True),
    sa.Column('journey_steps', sa.JSON(), nullable=True),
    sa.Column('distance_to_poi', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_tracking_id'), 'journey_tracking', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_journey_tracking_id'), table_name='journey_tracking')
    op.drop_table('journey_tracking')
    # ### end Alembic commands ###
